Repository 2info2-Grupo-3/FrontManutencao, pull requests merged in 2024-08, with the labels that each got.

#37 Style 35
  src/components/modalComps/addModal/addModalCliente.vue
  src/components/modalComps/dataModal/dataClienteModal.vue
  src/components/others/ClientsList.vue
Labels: Style

#38 Feat saidas&entradas
  src/assets/main.css
  src/components/Aside/LinksComp.vue
  src/components/modalComps/addModal/addEntradaModal.vue
  src/components/modalComps/addModal/addSaidaModal.vue
  src/components/others/EntradasComp.vue
  src/components/others/SaidasComp.vue
  src/router/index.js
  src/views/EntradasView.vue
  src/views/HomeView.vue
  src/views/SaidasView.vue
Labels: Feat

#39 Feat 25
  src/components/modalComps/addModal/addModalOrcamentos.vue
  src/components/modalComps/dataModal/dataOrcamentosModal.vue
  src/components/others/OrcamentosList.vue
  src/services/others/orcamentos.js
  src/stores/others/orcamentos.js
  src/views/HomeView.vue
Labels: Feat

#41 FIX: CRUD de peças funcionando
  src/components/modalComps/addModal/addPecaModal.vue
  src/components/modalComps/dataModal/dataPecaModal.vue
  src/components/others/PecasList.vue
  src/services/estoque/pecas.js
  src/stores/estoque/pecas.js
  src/views/HomeView.vue
Labels: Feat

#43 Feat 42
  src/components/Aside/AsideComp.vue
  src/components/modalComps/addModal/addModalOrcamentos.vue
  src/components/others/FaturamentoComp.vue
  src/components/others/OrcamentosList.vue
  src/views/HomeView.vue
Labels: Feat

#45 FEAT: views das rotas feitas #44
  src/App.vue
  src/components/Aside/LinksComp.vue
  src/router/index.js
  src/views/ClientesView.vue
  src/views/EntradasView.vue
  src/views/HomeView.vue
  src/views/OrcamentosView.vue
  src/views/PecasView.vue
  src/views/SaidasView.vue
  src/views/ServicosView.vue
Labels: Feat

#47 Chore: refanzendo estilo de orçamentos e serviços
  public/fundo-servico.png
  src/components/modalComps/addModal/addModalOrcamentos.vue
  src/components/modalComps/dataModal/dataClienteModal.vue
  src/components/modalComps/dataModal/dataOrcamentosModal.vue
  src/components/others/OrcamentosList.vue
  src/components/others/ServicosComp.vue
  src/views/HomeView.vue
Labels: Feat

#48 Fix orcamentos
  src/components/Aside/AsideComp.vue
  src/components/modalComps/addModal/addModalOrcamentos.vue
  src/components/others/FaturamentoComp.vue
  src/components/others/OrcamentosList.vue
Labels: Fix

#49 CHORE: chore homeview
  public/client-icon-white.svg
  public/cliente-view.png
  public/icon-elvis-blue.svg
  src/App.vue
  src/components/modalComps/dataModal/dataClienteModal.vue
  src/components/others/OrcamentosList.vue
  src/router/index.js
  src/views/HomeView.vue
Labels: Fix
